name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  make-release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: mrpack

      - uses: actions/download-artifact@v3
        with:
          name: onesix-modpack

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: drss*
